/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papeleriaconant;

import java.awt.event.ActionEvent;
import java.io.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author paulo
 */
public class Catalogos extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    public ArrayList<Producto> listaProductos;
    private String ruta;
    AgregarDatos aD = new AgregarDatos();

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    /**
     * Creates new form Main
     */
    public Catalogos() {
        initComponents();
        setModelo();
//        leerlista();
//        setDatos();
    }

    private void setModelo() {
        String[] cabecera = {"Id", "Nombre", "Descripcion", "Piezas", "Precio Unitario"};
        modelo.setColumnIdentifiers(cabecera);
        arteTbl.setModel(modelo);

    }

    private void escribirLista() {
        try {
            ObjectOutputStream escribiendoFichero = new ObjectOutputStream(
                    new FileOutputStream(ruta));
            escribiendoFichero.writeObject(listaProductos);
            escribiendoFichero.close();


        } catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }

//    Aqui recibe lo que tenga el archivo y lo mete a una listaProductos
    private void leerlista() {
        try {
            ObjectInputStream leyendoFichero = new ObjectInputStream(
                    new FileInputStream(ruta));
//
            listaProductos = (ArrayList<Producto>) leyendoFichero.readObject();
            leyendoFichero.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

//    vaciamos los datos de la lista en la tabla
    private void setDatos() {
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for (Producto theprod : listaProductos) {
            datos[0] = theprod.getIdProducto();
            datos[1] = theprod.getNombreDelProducto();
            datos[2] = theprod.getDescripcion();
            datos[3] = theprod.getCantidad();
            datos[4] = theprod.getPrecioUnitario();
            modelo.addRow(datos);
        }
        arteTbl.setModel(modelo);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        artePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arteTbl = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();
        agregarDatosPanel = new javax.swing.JPanel();
        verProductosBtn = new javax.swing.JButton();
        eliminarProductoBtn = new javax.swing.JButton();
        modificarProductoBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        catalogosComboBox = new javax.swing.JComboBox<>();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arteTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(arteTbl);

        agregarBtn.setText("AgregarProducto");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarDatosPanelLayout = new javax.swing.GroupLayout(agregarDatosPanel);
        agregarDatosPanel.setLayout(agregarDatosPanelLayout);
        agregarDatosPanelLayout.setHorizontalGroup(
            agregarDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        agregarDatosPanelLayout.setVerticalGroup(
            agregarDatosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        verProductosBtn.setText("Ver Productos");
        verProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductosBtnActionPerformed(evt);
            }
        });

        eliminarProductoBtn.setText("Eliminar un producto");
        eliminarProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoBtnActionPerformed(evt);
            }
        });

        modificarProductoBtn.setText("Modificar Producto");
        modificarProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoBtnActionPerformed(evt);
            }
        });

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        catalogosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adhesivos", "Artes", "Escritura", "Generales", "Papeles", "Regalos" }));
        catalogosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout artePanelLayout = new javax.swing.GroupLayout(artePanel);
        artePanel.setLayout(artePanelLayout);
        artePanelLayout.setHorizontalGroup(
            artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(artePanelLayout.createSequentialGroup()
                        .addComponent(agregarDatosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(artePanelLayout.createSequentialGroup()
                                .addComponent(eliminarProductoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modificarProductoBtn)
                                .addGap(11, 11, 11)
                                .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, artePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, artePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(catalogosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        artePanelLayout.setVerticalGroup(
            artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarDatosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(artePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarBtn)
                            .addComponent(eliminarProductoBtn)
                            .addComponent(modificarProductoBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(artePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verProductosBtn)
                    .addComponent(catalogosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(regresarBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(artePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(artePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:

        agregarDatosPanel.add(aD);
        aD.setRuta(ruta);
        aD.show();

    }//GEN-LAST:event_agregarBtnActionPerformed

    private void verProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductosBtnActionPerformed
        leerlista();
        setDatos();
        artePanel.repaint();


    }//GEN-LAST:event_verProductosBtnActionPerformed

    private void eliminarProductoBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_eliminarProductoBtnActionPerformed
        // TODO add your handling code here:

        if (arteTbl.getSelectedRow() == -1)
            return;

        //eliminamos la fila seleccionada de la lista

        listaProductos.remove(arteTbl.getSelectedRow());
        modelo.removeRow(arteTbl.getSelectedRow());
        System.out.println(listaProductos.toString());
        escribirLista();

    }//GEN-LAST:event_eliminarProductoBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Main regresarAlMain = new Main();
        regresarAlMain.setVisible(true);
        
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void catalogosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogosComboBoxActionPerformed
        // TODO add your handling code here:
         switch (catalogosComboBox.getSelectedIndex()) {
            case 0:
                setRuta("data/adhesivosProductos.obj");
                System.out.println("Entre al caso 0" + ruta);
                leerlista();
                setDatos();
//                this.repaint();
                break;
            case 1:
                setRuta( "data/artesProductos.obj");
                leerlista();
                setDatos();
//                this.repaint();
                break;
            case 2:
                setRuta("data/escrituraProductos.obj");
                leerlista();
                setDatos();
//                this.repaint();
                break;
            case 3:
                setRuta("data/generalesProductos.obj");
                leerlista();
                setDatos();
//                this.repaint();
                break;
            case 4:
                setRuta("data/papelesProductos.obj");
                leerlista();
                setDatos();
                this.repaint();
                break;
            case 5:
                setRuta("data/regalosProductos.obj");
                leerlista();
                setDatos();
//                this.repaint();
                break;
        }
    }//GEN-LAST:event_catalogosComboBoxActionPerformed

    private void modificarProductoBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        int filaSeleccionada = arteTbl.getSelectedRow();
        if (filaSeleccionada>=0){
            AgregarDatos modificar = new AgregarDatos(filaSeleccionada,ruta);
            agregarDatosPanel.add(modificar);
            modificar.show();
        }else
            JOptionPane.showMessageDialog(this,"Fila no seleccionada");

    }                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogos().setVisible(true);
            }
        });
    }

    public JTable getArteTbl() {
        return arteTbl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JPanel agregarDatosPanel;
    private javax.swing.JPanel artePanel;
    private javax.swing.JTable arteTbl;
    private javax.swing.JComboBox<String> catalogosComboBox;
    private javax.swing.JButton eliminarProductoBtn;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarProductoBtn;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JButton verProductosBtn;
    // End of variables declaration//GEN-END:variables
}
