/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papeleriaconant;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;

/**
 *
 * @author paulo
 */
public class Clientes extends javax.swing.JFrame {
    AgregarClientes aC = new AgregarClientes();
    DefaultTableModel modelo = new DefaultTableModel();
    public ArrayList<Usuarios> listaUsuarios;
    String ruta = "data/usuarios.obj";
    boolean archivoVacio;

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        setModelo();
    }
    //metodos
    private void setModelo() {
        String[] cabecera = {"Id", "Nombre", "Apellido", "edad", "Direccion","Tel","Correo"};
        modelo.setColumnIdentifiers(cabecera);
        usuariosTbl.setModel(modelo);

    }
    //agregamos los datos que existan en la lista en la tabla
    private void setDatos() {
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for (Usuarios theprod : listaUsuarios) {
            datos[0] = theprod.getIdCliente();
            datos[1] = theprod.getNombre();
            datos[2] = theprod.getApellido();
            datos[3] = theprod.getEdad();
            datos[4] = theprod.getDireccion();
            datos[5] = theprod.getNumeroDeTelefono();
            datos[6] = theprod.getCorreoElectronico();
            modelo.addRow(datos);
        }
        usuariosTbl.setModel(modelo);
    }
    private void escribirLista() {
        try {
            ObjectOutputStream escribiendoFichero = new ObjectOutputStream(
                    new FileOutputStream(ruta));
            escribiendoFichero.writeObject(listaUsuarios);
            escribiendoFichero.close();
            archivoVacio = false;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }
    private void leerlista() {
        try {
            ObjectInputStream leyendoFichero = new ObjectInputStream(
                    new FileInputStream(ruta));
            listaUsuarios = (ArrayList<Usuarios>) leyendoFichero.readObject();
            leyendoFichero.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBtn = new javax.swing.JButton();
        tablaUsuariosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTbl = new javax.swing.JTable();
        EliminarUSuario = new javax.swing.JButton();
        modificarUsuarioBtn = new javax.swing.JButton();
        agregarUsuarioBtn = new javax.swing.JButton();
        verProductosBtn = new javax.swing.JButton();
        modificarEliminarPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        usuariosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(usuariosTbl);

        EliminarUSuario.setText("Eliminar usuario");
        EliminarUSuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUSuarioActionPerformed(evt);
            }
        });

        modificarUsuarioBtn.setText("Modificar Usuario");
        modificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuarioBtnActionPerformed(evt);
            }
        });

        agregarUsuarioBtn.setText("Agregar usuario");
        agregarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioBtnActionPerformed(evt);
            }
        });

        verProductosBtn.setText("Ver Usuarios");
        verProductosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablaUsuariosPanelLayout = new javax.swing.GroupLayout(tablaUsuariosPanel);
        tablaUsuariosPanel.setLayout(tablaUsuariosPanelLayout);
        tablaUsuariosPanelLayout.setHorizontalGroup(
            tablaUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaUsuariosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablaUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tablaUsuariosPanelLayout.createSequentialGroup()
                        .addGroup(tablaUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(verProductosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tablaUsuariosPanelLayout.createSequentialGroup()
                                .addComponent(EliminarUSuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(modificarUsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(agregarUsuarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tablaUsuariosPanelLayout.setVerticalGroup(
            tablaUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaUsuariosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(tablaUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarUSuario)
                    .addComponent(modificarUsuarioBtn)
                    .addComponent(agregarUsuarioBtn))
                .addGap(18, 18, 18)
                .addComponent(verProductosBtn)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout modificarEliminarPanelLayout = new javax.swing.GroupLayout(modificarEliminarPanel);
        modificarEliminarPanel.setLayout(modificarEliminarPanelLayout);
        modificarEliminarPanelLayout.setHorizontalGroup(
            modificarEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        modificarEliminarPanelLayout.setVerticalGroup(
            modificarEliminarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modificarEliminarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(tablaUsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarEliminarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresarBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tablaUsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main regresarAlMain = new Main();
        regresarAlMain.setVisible(true);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void EliminarUSuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUSuarioActionPerformed
        // TODO add your handling code here:
        if (usuariosTbl.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Fila no seleccionada");
        }else{
            listaUsuarios.remove(usuariosTbl.getSelectedRow());
            modelo.removeRow(usuariosTbl.getSelectedRow());
            escribirLista();
        }
    }//GEN-LAST:event_EliminarUSuarioActionPerformed

    private void modificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarioBtnActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = usuariosTbl.getSelectedRow();
        if (filaSeleccionada>=0){
            AgregarClientes modificar = new AgregarClientes(filaSeleccionada,ruta);
            modificarEliminarPanel.add(modificar);
            modificar.show();
        }else
            JOptionPane.showMessageDialog(this,"Fila no seleccionada");
    }//GEN-LAST:event_modificarUsuarioBtnActionPerformed

    private void agregarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioBtnActionPerformed
        // TODO add your handling code here:
        modificarEliminarPanel.add(aC);
        aC.setRuta(ruta);
        aC.show();



    }//GEN-LAST:event_agregarUsuarioBtnActionPerformed

    private void verProductosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductosBtnActionPerformed
        // TODO add your handling code here:
        leerlista();
        setDatos();
        tablaUsuariosPanel.repaint();
    }//GEN-LAST:event_verProductosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarUSuario;
    private javax.swing.JButton agregarUsuarioBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel modificarEliminarPanel;
    private javax.swing.JButton modificarUsuarioBtn;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JPanel tablaUsuariosPanel;
    private javax.swing.JTable usuariosTbl;
    private javax.swing.JButton verProductosBtn;
    // End of variables declaration//GEN-END:variables
}
