/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papeleriaconant;

import javax.swing.table.DefaultTableModel;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author paulo
 */
public class ReporteDeVentas extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    private ArrayList<VentasProducidas> listaVentas = new ArrayList<VentasProducidas>();
    private VentasProducidas objVentasProducidas;
    String ruta = "data/ventas.obj";


    public ArrayList<VentasProducidas> getListaVentas() {
        return listaVentas;
    }

    public ReporteDeVentas() {
        super("Reporte de ventas");
        initComponents();
        leerListaDeVentas();
        setModelo();
        setDatos();
    }
    public void setModelo() {
        String[] cabecera = {"Dia","Mes","hora", "Nombre del producto Vendido ", "numero de piezas vendidas", "total"};
        modelo.setColumnIdentifiers(cabecera);
        tblReporte.setModel(modelo);
    }
    private void setDatos() {
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for (VentasProducidas theprod : listaVentas) {
            datos[0] = theprod.getDia();
            datos[1] = theprod.getMes();
            datos[2] = theprod.getHora();
            datos[3] = theprod.getNombreProductosVendidos();
            datos[4] = theprod.getNumeroDePiezasDeProductosVendidos();
            datos[5] = theprod.getTotalDeVenta();
            modelo.addRow(datos);
        }
        tblReporte.setModel(modelo);

    }
    public void leerListaDeVentas() {
        try {
            ObjectInputStream leyendoFichero = new ObjectInputStream(
                    new FileInputStream(ruta));
//
            listaVentas = (ArrayList<VentasProducidas>) leyendoFichero.readObject();
            leyendoFichero.close();
        } catch (
                FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    public void setDatosDia(){
        int diaMasActual = 0;
        int mesMasActual = 0;
        for (VentasProducidas vent:listaVentas) {
            if (vent.getDia() > diaMasActual){
                diaMasActual = vent.getDia();
            }
            if (vent.getMes() > mesMasActual){
                mesMasActual = vent.getMes();
            }

        }
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for (VentasProducidas theprod : listaVentas) {
            if (theprod.getDia() == diaMasActual && theprod.getMes() == mesMasActual){

                datos[0] = theprod.getDia();
                datos[1] = theprod.getMes();
                datos[2] = theprod.getHora();
                datos[3] = theprod.getNombreProductosVendidos();
                datos[4] = theprod.getNumeroDePiezasDeProductosVendidos();
                datos[5] = theprod.getTotalDeVenta();
                modelo.addRow(datos);
            }
        }
        tblReporte.setModel(modelo);

    }
    public void setDAtosMes(){
        int mesMasActual = 0;
        for (VentasProducidas vent:listaVentas) {
            if (vent.getMes() > mesMasActual){
                mesMasActual = vent.getMes();
            }

        }
        Object[] datos = new Object[modelo.getColumnCount()];
        modelo.setRowCount(0);
        for (VentasProducidas theprod : listaVentas) {
            if (theprod.getMes() == mesMasActual){

                datos[0] = theprod.getDia();
                datos[1] = theprod.getMes();
                datos[2] = theprod.getHora();
                datos[3] = theprod.getNombreProductosVendidos();
                datos[4] = theprod.getNumeroDePiezasDeProductosVendidos();
                datos[5] = theprod.getTotalDeVenta();
                modelo.addRow(datos);
            }
        }
        tblReporte.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        diaBtn = new javax.swing.JButton();
        mesBtn = new javax.swing.JButton();
        semanaBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        diaBtn.setText("Dia");
        diaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaBtnActionPerformed(evt);
            }
        });

        mesBtn.setText("Mes");
        mesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesBtnActionPerformed(evt);
            }
        });

        semanaBtn.setText("Todas las ventas");
        semanaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanaBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(diaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(semanaBtn)
                        .addGap(44, 44, 44)
                        .addComponent(mesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaBtn)
                    .addComponent(semanaBtn)
                    .addComponent(mesBtn))
                .addGap(61, 61, 61)
                .addComponent(jButton4)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaBtnActionPerformed
        // TODO add your handling code here:
        setDatosDia();
        this.repaint();

    }//GEN-LAST:event_diaBtnActionPerformed

    private void semanaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanaBtnActionPerformed
        // TODO add your handling code here:
        setDatos();
        this.repaint();
    }//GEN-LAST:event_semanaBtnActionPerformed

    private void mesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesBtnActionPerformed
        // TODO add your handling code here:
        setDAtosMes();
        this.repaint();
    }//GEN-LAST:event_mesBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        Main regresarAlMain = new Main();
        regresarAlMain.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDeVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diaBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mesBtn;
    private javax.swing.JButton semanaBtn;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
